<?php

/**
 * @file
 * Big Blue Button - Enables universities and colleges to deliver a high-quality
 * learning experience.
 * 
 * @author
 * Stefan Auditor <stefan.auditor@erdfisch.de>
 */

/**
 * Implementation of hook_views_api().
 */
function bbb_views_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'bbb') . '/includes',
  );
}

/**
 * Implement hook_views_handlers().
 */
function bbb_views_handlers() {
  return array(
    'info' => array(
      'path' => drupal_get_path('module', 'bbb') . '/includes',
    ),
    'handlers' => array(
      'views_handler_field_bbb_join_attendee' => array(
        'parent' => 'views_handler_field',
      ),
      'views_handler_field_bbb_join_moderator' => array(
        'parent' => 'views_handler_field',
      ),
    ),
  );
}
